export default {
	customBookmarks: 'My bookmarks',
	sharedBookmarks: 'Shared bookmarks',
	addCustomBookmark: 'Add bookmark',
	addSharedBookmark: 'Add shared bookmark',
	addCustomBookmarkText: 'Enter information about your new bookmark.',
	bookmarkVisibilitySwitchHelperText: 'Set visibility for this bookmark.',
	noBookmarkFound: 'No Bookmark Found.',
	subscribeToBookmarkText:
		'Enter UUID of already existing bookmark you want to subscribe to.',
	notSignedIn: 'User is not signed in.',
	invalidUUID: 'Invalid UUID.',
	nonExistingUUID: 'Non existing UUID.',
	error: 'Unexpected error has occurred.',
	bookmarkDescription: 'Description',
	imageUrl: 'Image URL',
	name: 'Name',
	title: 'Title',
	public: 'Public',
	private: 'Private',
	cancel: 'Cancel',
	submit: 'Submit',
	bookmarkName: 'Bookmark name',
	isFolder: 'Is a folder?',
	folder: 'Folder',
	yes: 'Yes',
	no: 'No',
	areYouSureDelete: 'Do you really want to remove this item?',
	login: 'Login',
	logout: 'Logout',
	edit: 'Edit',
	signUp: 'Sign Up',
	signIn: 'Sign In',
	notFound: 'Not Found'
};
